prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix owl: <http://www.w3.org/2002/07/owl#>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>

prefix : <http://data.krw.d2s.labs.vu.nl/group6/findaslot/vocab/>
prefix data: <http://data.krw.d2s.labs.vu.nl/group6/findaslot/resource/>
prefix geo: <http://www.w3.org/2003/01/geo/wgs84_pos#>
prefix math: <http://www.w3.org/2005/xpath-functions/math#>
prefix dbo: <http://dbpedia.org/ontology/>

select distinct ?venue ?slot ?slat ?slong ?elat ?elong ?dist
where {
  ?eslot a :ParkingSlot .
  ?eslot rdfs:label ?slot .
  ?eslot dbo:location ?slocation .
  ?slocation geo:lat ?slat ; geo:long ?slong .
  
  data:Podium_Mozaïek a :Venue .
  data:Podium_Mozaïek rdfs:label ?venue .
  data:Podium_Mozaïek dbo:location ?elocation .
  ?elocation geo:lat ?elat ; geo:long ?elong .
  
  bind(xsd:double(?slat) * math:pi() / xsd:double(180) as ?la1) .
  bind(xsd:double(?slong) * math:pi() / xsd:double(180) as ?lo1) .
  bind(xsd:double(?elat) * math:pi() / xsd:double(180) as ?la2) .
  bind(xsd:double(?elong) * math:pi() / xsd:double(180) as ?lo2) .
  bind(?lo2 - ?lo1 as ?l) .
  bind(math:acos(math:sin(?la2)*math:sin(?la1) + math:cos(?la1)*math:cos(?la1)*math:cos(?l)) * xsd:double(6371000) as ?dist) .
}
order by ?dist
