prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix owl: <http://www.w3.org/2002/07/owl#>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>

prefix : <http://data.krw.d2s.labs.vu.nl/group6/findaslot/vocab/>
prefix dbo: <http://dbpediaorg/ontology/>

select distinct ?evenue ?venue
where { 
	?evenue a :Venue .
  	?evenue rdfs:label ?venue .
}